### ISSUE TITLE
Consider using prettier

### ISSUE THREAD

**Issue by tobiaslins** [LiskHQ/lisk-js#416] opened 2017-10-11 09:58 UTC
In order to be even more consistent it would be good using prettier. 
It will **not** replace `ESLint`because it is no linter.

- We would have an consistent code style for formatting
- We could add a precommit hook to format all files
- Define if we want to keep all eslint rules or switch to some recommendations from prettier

## Example for current differences:

**Old**
```js
naclFactory.instantiate((nacl) => {
  naclInstance = nacl;
});

export {
  crypto,
  transaction,
  api,
  time,
  Mnemonic,
};
```

**After prettier**
```js
naclFactory.instantiate(nacl => {  // removed braces if only one parameter
  naclInstance = nacl;
});

export { crypto, transaction, api, time, Mnemonic }; // only breaks into new lines if length too long
```

For those who didn't use prettier yet:
https://engineering.hexacta.com/why-arent-you-using-prettier-4fe0a77713e8

**Comment by willclarktech** [comment] 2017-10-11 10:08
I'm actually totally in favour of this. I've not used Prettier, but as mentioned [here](https://github.com/LiskHQ/lisk/issues/672#issuecomment-324849081) my experience with [elm-format](https://github.com/avh4/elm-format) is very positive.

**Comment by willclarktech** [comment] 2017-10-16 14:33
Applying prettier to current state of `src` and `test` with `prettier --single-quote --trailing-comma all --use-tabs --write "{src,test}"` leads to 58 errors:

- The vast majority are `arrow-parens` which would be fixed with a new release of [eslint-config-lisk-base](https://github.com/LiskHQ/eslint-config-lisk-base/commit/07a6cb53377d1b36049fd97448197f8a35157b17)
- 12 errors caused by 3 occurrences of a ternary operator spanning multiple lines where prettier and eslint disagree about how much indentation there should be. It appears that Prettier cannot be configured. Eslint [can be turned off](https://eslint.org/docs/rules/indent#ignorednodes) in this respect but probably not configured.
- 2 errors caused by 1 occurrence of mixing `+` with `*`. We can [turn this off](https://eslint.org/docs/rules/no-mixed-operators#options) in eslint, but it seems Prettier cannot be configured. I guess we should all know our operator precedence, but I think this is quite a nice rule to have just in case.
- 1 occurrence of `curly` where Prettier removes a curly brace for an `if` statement block with only one statement (that spans multiple lines). We can easily [turn this off in eslint](https://eslint.org/docs/rules/curly#multi) but I personally like the rule. It seems Prettier cannot be configured.
- 1 occurrence of `no-confusing-arrow` which is an eslint rule I personally find annoying anyway.

**Closed** 2017-10-19 07:17 UTC
Labels: medium, standards
